#ifndef _ESPAPP_Parameters_HTTP_Server_h
#define _ESPAPP_Parameters_HTTP_Server_h


#define ESPAPP_HTTP_SITE_INDEX 1
#define ESPAPP_HTTP_SITE_FIRMWARE_COMMAND 100
#define ESPAPP_HTTP_SITE_REBOOT 101

#define ESPAPP_HTTP_SITE_FILE_EXPLORER 110


#define ESPAPP_HTTP_SITE_FILE_EXPLORER_COMMAND_UPLOAD 0
#define ESPAPP_HTTP_SITE_FILE_EXPLORER_COMMAND_DELETE 1

#define ESPAPP_HTTP_SITE_FIRMWARE_COMMAND_REBOOT 0

#define ESPAPP_HTTP_HTML_MAX_RESPONSE_SIZE 2048
#define ESPAPP_HTTP_RESPONSE_CODE_OK 200
#define ESPAPP_HTTP_RESPONSE_CODE_NOT_FOUND 404
#define ESPAPP_HTTP_REQUEST_PARAMETER_1_MAX_LENGTH 3244

#define ESPAPP_HTTP_SITE_REFRESH_REBOOT "15"


#endif // _ESPAPP_Parameters_h